name: Generate ASCII Artwork with cowsay

on: 
  [push]

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate ASCII Artwork with cowsay
        run: |
          echo $PWD
          cd .github/workflows
          chmod +x ./generate-ascii.sh
          ./generate-ascii.sh