name: Generate ASCII Artwork Phases

on:
  [push]

jobs:
  ascii_build_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Checkout Repo Files
      run: |
        pwd
        ls -ltra

    - name: Build Cowsay CMD
      run: |
        chmod +x ./.github/scripts/ascii-script-build.sh
        ./.github/scripts/ascii-script-build.sh

    - name: Upload Dragon text file
      uses: actions/upload-artifact@v4
      with:
        name: dragon-ascii-artifact
        path: dragon.txt
        
  ascii_test_job:
    needs: ascii_build_job
    runs-on: ubuntu-latest
    steps:
    - name: Download Dragon text file
      uses: actions/download-artifact@v4
      with:
        name: dragon-ascii-artifact

    - name: Checkout Repo Files
      run: |
        echo "Checking out Repo Files"
        pwd
        echo "Listing Files"
        ls -ltra
        echo "Listing Parent Directory"
        ls -ltra ../

    - name: Test Cowsay CMD
      run: grep -i "dragon" dragon.txt

  ascii_deploy_job:
    needs: [ ascii_build_job, ascii_test_job ]
    runs-on: ubuntu-latest
    steps:
    - name: Download Dragon text file
      uses: actions/download-artifact@v4
      with:
        name: dragon-ascii-artifact

    - name: Deploy Cowsay CMD
      run: |
        cat dragon.txt
        echo "Deploying ASCII Artwork"
