name: Generate ASCII Artwork Phases

on:
  [push]

jobs:
  ascii_build_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Checkout Repo Files
      run: |
        pwd
        ls -ltra

    - name: Build Cowsay CMD
      run: |
        chmod +x ./.github/scripts/ascii-script-build.sh
        ./.github/scripts/ascii-script-build.sh
        
  ascii_test_job:
    needs: ascii_build_job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Checkout Repo Files
      run: |
        pwd
        ls -ltRa

    - name: Test Cowsay CMD
      run: |
        chmod +x ./.github/scripts/ascii-script-test.sh
        ./.github/scripts/ascii-script-test.sh

  ascii_deploy_job:
    needs: [ ascii_build_job, ascii_test_job ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Deploy Cowsay CMD
      run: |
        chmod +x ./.github/scripts/ascii-script-deploy.sh
        ./.github/scripts/ascii-script-deploy.sh
