name: Matrix Configuration

on: 
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        node-version: [15.x, 16.x]
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        images: [hello-world, alpine]
        exclude:
          - node-version: 15.x
            images: alpine
            os: windows-latest
          - node-version: 16.x
            images: alpine
            os: windows-latest
        include:
          - images: alpine
            os: ubuntu-20.04
            node-version: 15.x
          - images: alpine
            os: ubuntu-latest
            node-version: 16.x
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Display Node.js Version
      run: node --version

    - name: Echo Docker Info
      run: docker info

    - name: Run Image on ${{ matrix.os }}
      run: docker run ${{ matrix.images }}