name: Exploring Variables and Secrets at Step Level

on: 
  push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build
      env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Building Docker Image"
        echo docker build -t ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest .

    - name: Docker Login
      env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Building Docker Image"
        echo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    
    - name: Docker Publish
      env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: github-actions-nginx
      run: |
        echo "Publishing Docker Image"
        echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Docker Run
      env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: github-actions-nginx
      run: |
        echo "Running Docker Image"
        echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

############################ end environment variables at step level ############################